version: "3"

services:
  db:
    container_name: postgres-container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zzz123
  pgAdmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:6.11
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ignas@admin.com
      PGADMIN_DEFAULT_PASSWORD: zzz123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"
  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.3.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
networks:
  es-net:
    driver: bridge
